insert into GCM_INFO(APP_CODE, APP_NAME, REG_ID, API_KEY, RETRY_CNT) VALUE("ST", "S톡", "AIzaSyDVa2kUvarIvIcNLueiOw22fh2HSacn4Bs", "508784257206", 5);
insert into GCM_INFO(APP_CODE, APP_NAME, REG_ID, API_KEY, RETRY_CNT) VALUE("AC", "앱1", "AIzaSyDVa2kUvarIvIcNLueiOw22fh2HSacn5Bs", "508784257201", 5);


insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 1, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 2, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 3, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 1, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 2, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 3, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 1, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 2, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 3, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 1, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 2, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 3, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 1, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 2, NOW());
insert into GCM_SEND_MESSAGE(TITLE, MESSAGE, STATUS_CODE, REG_DATE) VALUE("테스트1", "안녕하세요.", 3, NOW());
